name: Trigger auto deployment for albumui

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/**'
    - '.github/workflows/albumui-AutoDeployTrigger-cd5e512c-0d9b-43d5-9cf4-64703d08295e.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ca2ad69f7d00acr.azurecr.io
          username: ${{ secrets.ALBUMUI_REGISTRY_USERNAME }}
          password: ${{ secrets.ALBUMUI_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ca2ad69f7d00acr.azurecr.io/albumui:${{ github.sha }}
          file: src/Dockerfile
          context: src/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ALBUMUI_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n albumui -g admin_rg_8071 --server ca2ad69f7d00acr.azurecr.io --username  ${{ secrets.ALBUMUI_REGISTRY_USERNAME }} --password ${{ secrets.ALBUMUI_REGISTRY_PASSWORD }}
            az containerapp update -n albumui -g admin_rg_8071 --image ca2ad69f7d00acr.azurecr.io/albumui:${{ github.sha }}
